spring:
  cloud:
    config:
      enabled: false
  application:
    name: RIBBON-TEST
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}